### ISSUE TITLE
Setup website

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/hematite.piston.rs#1]
What do we need?

**Comment by fenhl** [comment]
Website is up, we need a theme which is consistent with the main website and blog (see #6).

**Comment by fenhl** [comment]
And someone with access to piston.rs needs to set up the forwarding.

**Comment by leonkunert** [comment]
Forwarding has been set up.

see #5

**Comment by agmcleod** [comment]
looks awesome :)

**Comment by bvssvni** [comment]
Done.
